/**
 * Machine-readable fraud triggers. Persisted on user risk hash and in API responses.
 */
export enum CoinflipFraudReason {
  WIN_RATE_HIGH_CONFIDENCE = 'WIN_RATE_HIGH_CONFIDENCE',
  EV_PROFIT_ANOMALY = 'EV_PROFIT_ANOMALY',
  COLLUSION_REPEATED_PAIR = 'COLLUSION_REPEATED_PAIR',
  COLLUSION_WIN_IMBALANCE = 'COLLUSION_WIN_IMBALANCE',
  MONEY_FLOW_RING = 'MONEY_FLOW_RING',
  MONEY_FLOW_SKEW = 'MONEY_FLOW_SKEW',
  BOT_TIMING_LOW_VARIANCE = 'BOT_TIMING_LOW_VARIANCE',
  BET_SPIKE_VS_HISTORY = 'BET_SPIKE_VS_HISTORY',
  SHARED_IP_CLUSTER = 'SHARED_IP_CLUSTER',
  SHARED_DEVICE_CLUSTER = 'SHARED_DEVICE_CLUSTER',
  MULTI_ACCOUNT_GRAPH_CLUSTER = 'MULTI_ACCOUNT_GRAPH_CLUSTER',
  SUSPICIOUS_GAME_TIMING = 'SUSPICIOUS_GAME_TIMING',
  MANUAL_STAFF_FLAG = 'MANUAL_STAFF_FLAG',
}
