export const STAFF_AUTH_REPOSITORY = Symbol('STAFF_AUTH_REPOSITORY');
export const PASSWORD_VERIFIER = Symbol('PASSWORD_VERIFIER');
export const TOKEN_ISSUER = Symbol('TOKEN_ISSUER');
export const AUTH_ATTEMPT_LOGGER = Symbol('AUTH_ATTEMPT_LOGGER');
export const TWO_FACTOR_CHALLENGE_REPOSITORY = Symbol(
  'TWO_FACTOR_CHALLENGE_REPOSITORY',
);
export const TWO_FACTOR_MAILER = Symbol('TWO_FACTOR_MAILER');
export const OTP_HASHER = Symbol('OTP_HASHER');
export const TWO_FACTOR_CODE_GENERATOR = Symbol('TWO_FACTOR_CODE_GENERATOR');
